name: Feature request
description: Suggest an enhancement to twopow.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: Scope acknowledgement
      options:
        - label: I understand twopow's base is, and will remain, 2.
          required: true
